/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2021-12-19 00:20:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

public final class personelekleY_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headery.jsp", out, false);
      out.write("\n");
      out.write("    <div id=\"body\" class=\"active\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-white bg-white\">\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                <ul class=\"nav navbar-nav ml-auto\">\n");
      out.write("\n");
      out.write("                    <li class=\"nav-item dropdown\">\n");
      out.write("                        <div class=\"nav-dropdown\">\n");
      out.write("                            <a href=\"\" class=\"nav-item nav-link dropdown-toggle text-secondary\" data-toggle=\"dropdown\"><i class=\"fas fa-user\"></i> <span>Yönetici</span> <i style=\"font-size: .8em;\" class=\"fas fa-caret-down\"></i></a>\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-right nav-link-menu\">\n");
      out.write("                                <ul class=\"nav-list\">\n");
      out.write("                                    <li><a href=\"cikisyapY.jsp\" class=\"dropdown-item\"><i class=\"fas fa-sign-out-alt\"></i> Çıkış Yap</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("\n");
      out.write("                </div>     \n");
      out.write("\n");
      out.write("                ");

                    Connection con;
                    String msg = "";
                    String color = "";
                    if (request.getMethod().compareToIgnoreCase("post") == 0) {
                        try {
                            String isimp = request.getParameter("isimp");
                            String soyisimp = request.getParameter("soyisimp");
                            String kullaniciAdip = request.getParameter("kullaniciAdip");
                            String emailp = request.getParameter("emailp");
                            String sifrep = request.getParameter("sifrep");
                            String adresp = request.getParameter("adresp");
                            String telp = request.getParameter("telp");

                            Class.forName("com.mysql.jdbc.Driver");
                            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppyonetim", "root", "root");
                            String query = "INSERT INTO personelreg(isimp,soyisimp,kullaniciAdip,emailp,sifrep,adresp,telp) VALUES (?,?,?,?,?,?,?)";

                            PreparedStatement pst = con.prepareStatement(query);

                            pst.setString(1, isimp);
                            pst.setString(2, soyisimp);
                            pst.setString(3, kullaniciAdip);
                            pst.setString(4, emailp);
                            pst.setString(5, sifrep);
                            pst.setString(6, adresp);
                            pst.setString(7, telp);

                            pst.executeUpdate();

                            color = "green";
                            msg = "Personel Olarak Kaydınız Başarıyla Gerçekleştirilmiştir. Artık Sisteme Giriş Yapabilirsiniz...";

                        } catch (Exception ex) {
                            ex.printStackTrace();
                            color = "red";
                            msg = "Personel Olarak Kaydınız Oluşturulurken Beklenmedik Bir Sorun Çıktı, Daha Sonra Tekrar Deneyiniz...";
                        }
                    }
                
      out.write("         \n");
      out.write("\n");
      out.write("                <div class=\"form-group col-12 p-0\">\n");
      out.write("                    <h4 style=\"color:");
      out.print( color);
      out.write('"');
      out.write('>');
      out.print( msg);
      out.write("</h4>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <form id=\"form\" method=\"post\" action=\"personelekleY.jsp\" class=\"form-horizontal\">\n");
      out.write("                    <hr/>\n");
      out.write("                    <div class=\"col-lg-12\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-header\">Yeni Personel Ekle</div>\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\"></h5>\n");
      out.write("                                <form class=\"form-horizontal\">    \n");
      out.write("\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label >Adınız:</label>\n");
      out.write("                                        <input type=\"text\" name=\"isimp\" class=\"form-control\" id=\"isimp\" placeholder=\"Adınızı giriniz\"/>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label >Soyadınız:</label>\n");
      out.write("                                        <input type=\"text\" name=\"soyisimp\" class=\"form-control\" id=\"soyisimp\" placeholder=\"Soyadınızı giriniz\"/>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Kullanıcı Adınız:</label>\n");
      out.write("                                        <input type=\"text\" name=\"kullaniciAdip\" class=\"form-control\" id=\"kullaniciAdip\" placeholder=\"Kullanıcı adınızı belirleyiniz\"/>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>E-Posta Adresiniz:</label>\n");
      out.write("                                        <input type=\"text\" name=\"emailp\" class=\"form-control\" id=\"emailp\" placeholder=\"E-Posta adresinizi giriniz\">\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Şifreniz:</label>\n");
      out.write("                                        <input type=\"password\" name=\"sifrep\" class=\"form-control\" id=\"sifrep\" placeholder=\"Şifrenizi oluşturunuz\">\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Adresiniz:</label>\n");
      out.write("                                        <input type=\"text\" name=\"adresp\" class=\"form-control\" id=\"adresp\" placeholder=\"Adres bilgilerinizi giriniz\">\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Telefon Numaranız:</label>\n");
      out.write("                                        <input type=\"text\" name=\"telp\" class=\"form-control\" id=\"telp\" placeholder=\"Telefon numaranızı giriniz\">\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"line\"></div><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    <div class=\"form-group row\">\n");
      out.write("                                        <div class=\"col-sm-4 offset-sm-2\">\n");
      out.write("                                            <a href=\"anasayfaY.jsp\"><button class=\"btn btn-secondary mb-2\"><i class=\"fas fa-times\"></i> Anasayfa</button></a>\n");
      out.write("                                            <a href=\"personelekleY.jsp\"><button type=\"submit\" class=\"btn btn-primary mb-2\"><i class=\"fas fa-save\"></i> Kaydet</button></a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>       \n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"assets/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("<script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script src=\"assets/vendor/chartsjs/Chart.min.js\"></script>\n");
      out.write("<script src=\"assets/js/dashboard-charts.js\"></script>\n");
      out.write("<script src=\"assets/js/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
