/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2021-12-19 00:53:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

public final class yoneticiKaydol_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>    \n");
      out.write("    <title>Proje / Personel Yönetim Sistemi</title>		\n");
      out.write("    <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/> \n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        img {\n");
      out.write("            display: block;\n");
      out.write("            margin-left: auto;\n");
      out.write("            margin-right: auto;\n");
      out.write("        }\n");
      out.write("    </style>  \n");
      out.write("    <div class=\"container phome\">\n");
      out.write("        <div class=\"admin-page-title\">\n");
      out.write("            <h2>Proje / Personel Yönetim Sistemi</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row page-card\">\n");
      out.write("            <div class=\"col-lg-8 offset-1\">                    \n");
      out.write("                <ul class=\"nav nav-pills nav-fill\">                  \n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link active\" href=\"yoneticiKaydol.jsp\">Yönetici Kayıt</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link unactive\" href=\"personelKaydol.jsp\">Personel Kayıt</a>\n");
      out.write("                    </li>                \n");
      out.write("                </ul>                       \n");
      out.write("            </div>           \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            Connection con;
            String msg = "";
            String color = "";
            if (request.getMethod().compareToIgnoreCase("post") == 0) {
                try {
                    String isim = request.getParameter("isim");
                    String soyisim = request.getParameter("soyisim");
                    String kullaniciAdi = request.getParameter("kullaniciAdi");
                    String email = request.getParameter("email");
                    String sifre = request.getParameter("sifre");
                    String adres = request.getParameter("adres");
                    String tel = request.getParameter("tel");

                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppyonetim", "root", "root");
                    String query = "INSERT INTO yoneticireg(isim,soyisim,kullaniciAdi,email,sifre,adres,tel) VALUES (?,?,?,?,?,?,?)";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, isim);
                    pst.setString(2, soyisim);
                    pst.setString(3, kullaniciAdi);
                    pst.setString(4, email);
                    pst.setString(5, sifre);
                    pst.setString(6, adres);
                    pst.setString(7, tel);

                    pst.executeUpdate();

                    color = "green";
                    msg = "Yönetici Olarak Kaydınız Başarılya Gerçekleştirilmiştir. Artık Sisteme Giriş Yapabilirsiniz...";

                } catch (Exception ex) {
                    ex.printStackTrace();
                    color = "red";
                    msg = "Yönetici Olarak Kaydınız Oluşturulurken Beklenmedik Bir Sorun Çıktı, Daha Sonra Tekrar Deneyiniz...";
                }
            }
        
      out.write("       \n");
      out.write("\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <h4 style=\"color:");
      out.print( color);
      out.write('"');
      out.write('>');
      out.print( msg);
      out.write("</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row page-card\">\n");
      out.write("            <div class=\"col-lg-8 offset-1 jumbotron\">\n");
      out.write("                <h3 class=\"text-primary\">Yönetici Olarak Kaydol</h3><br />\n");
      out.write("\n");
      out.write("                <form id=\"form\" method=\"post\" action=\"yoneticiKaydol.jsp\" class=\"form-horizontal\">\n");
      out.write("                    <hr/>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label >Adınız:</label>\n");
      out.write("                        <input type=\"text\" name=\"isim\" class=\"form-control\" id=\"isim\" placeholder=\"Adınızı giriniz\"/>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label >Soyadınız:</label>\n");
      out.write("                        <input type=\"text\" name=\"soyisim\" class=\"form-control\" id=\"soyisim\" placeholder=\"Soyadınızı giriniz\"/>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>Kullanıcı Adınız:</label>\n");
      out.write("                        <input type=\"text\" name=\"kullaniciAdi\" class=\"form-control\" id=\"kullaniciAdi\" placeholder=\"Kullanıcı adınızı belirleyiniz\"/>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>E-Posta Adresiniz:</label>\n");
      out.write("                        <input type=\"text\" name=\"email\" class=\"form-control\" id=\"email\" placeholder=\"E-Posta adresinizi giriniz\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>Şifreniz:</label>\n");
      out.write("                        <input type=\"password\" name=\"sifre\" class=\"form-control\" id=\"sifre\" placeholder=\"Şifrenizi oluşturunuz\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>Adresiniz:</label>\n");
      out.write("                        <input type=\"text\" name=\"adres\" class=\"form-control\" id=\"adres\" placeholder=\"Adres bilgilerinizi giriniz\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>Telefon Numaranız:</label>\n");
      out.write("                        <input type=\"text\" name=\"tel\" class=\"form-control\" id=\"tel\" placeholder=\"Telefon numaranızı giriniz\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <a href=\"index.jsp\"><button type=\"submit\" class=\"btn btn-primary \">KAYDOL</button><a/>\n");
      out.write("\n");
      out.write("                        <br>\n");
      out.write("\n");
      out.write("                        </form>\n");
      out.write("\n");
      out.write("                        <a>Zaten bir hesabınız var mı? <a href=\"yoneticiGiris.jsp\">Giriş Yap!</a></a>\n");
      out.write("                        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
